server:
  port: 8080

logging:
  level:
    ROOT: DEBUG
    com.mycomp.test: DEBUG
    
spring:
  service:
    name: crm
  devtools:
    restart:
      enabled: true

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:product;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password:
    hikari:
      poolName: Hikari
      auto-commit: false
  h2:
    console:
      enabled: true
  jpa:
    database-platform: io.github.jhipster.domain.util.FixedH2Dialect
    show-sql: true
  liquibase:
    # Remove 'faker' if you do not want the sample data to be loaded automatically
    contexts: faker
